######################################################################
# Automatically generated by qmake (1.07a) Tue Aug 25 10:24:05 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += datafield.h screenmaker.h testwidget.h mockeditfield.h
SOURCES += datafield.cpp main.cpp screenmaker.cpp testwidget.cpp mockeditfield.cpp
